import * as nodeFs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import { afterEach, beforeEach, describe, expect, it, vi, type Mock } from "vitest";

const paths = vi.hoisted(() => ({ pluginDir: "", dataDir: "", native: [] as string[] }));

// resolve the persistor's game paths into per-test temp dirs
vi.mock("./gameSupport", () => ({
  gameSupported: () => true,
  gameDataPath: () => paths.dataDir,
  pluginPath: () => paths.pluginDir,
  pluginFormat: () => "fallout4",
  nativePlugins: () => paths.native,
}));

import type { ILoadOrder } from "../types/ILoadOrder";
import PluginPersistor from "./PluginPersistor";

const VORTEX_HEADER = "# Automatically generated by Vortex";

// settle window for the persistor's internal fire-and-forget promises; serialize
// schedules its write 200ms out, so callers that must outlast it pass a longer wait
const settle = (ms: number = 50) => new Promise((resolve) => setTimeout(resolve, ms));

describe("PluginPersistor", () => {
  let persistor: PluginPersistor;
  // stands in for the redux loadOrder hive, keyed by plugin id
  let hive: Record<string, Partial<ILoadOrder>>;
  let hydrateSpy: Mock;

  // mirrors ExtensionManager.hydrateFromPersistor: enumerate getAllKeys, getItem each,
  // REPLACE the hive wholesale with the result
  const hydrate = async () => {
    const keys = await persistor.getAllKeys();
    const next: Record<string, Partial<ILoadOrder>> = {};
    for (const key of keys) {
      next[key[0]] = JSON.parse(await persistor.getItem(key));
    }
    hive = next;
  };

  beforeEach(async () => {
    paths.pluginDir = nodeFs.mkdtempSync(path.join(os.tmpdir(), "plugin-persistor-"));
    paths.dataDir = nodeFs.mkdtempSync(path.join(os.tmpdir(), "plugin-data-"));
    paths.native = [];
    // one plugin enabled and persisted (the install-time single-plugin case) plus one
    // known-but-disabled plugin whose position only the persistor remembers
    nodeFs.writeFileSync(
      path.join(paths.pluginDir, "plugins.txt"),
      `${VORTEX_HEADER}\r\n*Old.esp\r\nParked.esp\r\n`,
      { encoding: "latin1" },
    );
    hive = {};
    persistor = new PluginPersistor(vi.fn(), () => false);
    hydrateSpy = vi.fn(hydrate);
    persistor.setResetCallback(hydrateSpy);
    await persistor.loadFiles("skyrimse");
    persistor.setKnownPlugins({ "old.esp": "Old.esp" });
    // wait for the scheduled serialize to land.
    await vi.waitFor(() =>
      expect(
        nodeFs.readFileSync(path.join(paths.pluginDir, "plugins.txt"), "latin1"),
      ).not.toContain("Parked.esp"),
    );
    await hydrate();
  });

  afterEach(async () => {
    await persistor.disable();
    nodeFs.rmSync(paths.pluginDir, { recursive: true, force: true });
    nodeFs.rmSync(paths.dataDir, { recursive: true, force: true });
  });

  it("does not rehydrate state from a known-plugins refresh", async () => {
    const callsBefore = hydrateSpy.mock.calls.length;

    persistor.setKnownPlugins({ "old.esp": "Old.esp", "multi.esp": "Multi.esp" });
    await settle();

    expect(hydrateSpy.mock.calls.length).toBe(callsBefore);
  });

  it("keeps a state-only enable through a known-plugins refresh (collection postprocess shape)", async () => {
    // the postprocess parser just enabled a multi-plugin mod's plugin in redux; the
    // debounced persistor diff has NOT run yet when updatePluginList refreshes the
    // known-plugin set
    hive["multi.esp"] = { enabled: true, loadOrder: 1 };

    persistor.setKnownPlugins({ "old.esp": "Old.esp", "multi.esp": "Multi.esp" });
    await settle();

    expect(hive["multi.esp"]?.enabled).toBe(true);
  });

  describe("external plugins.txt changes", () => {
    const pluginsFile = () => path.join(paths.pluginDir, "plugins.txt");

    it("does not adopt a foreign file while the keep/revert choice is pending", async () => {
      let choose: (choice: "keep" | "revert") => void;
      const onExternalChange = vi.fn(
        () => new Promise<"keep" | "revert">((resolve) => (choose = resolve)),
      );
      persistor.setExternalChangeCallback(onExternalChange);

      // the game/launcher rewrote the file: no Vortex header, different content
      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();

      expect(onExternalChange).toHaveBeenCalledTimes(1);
      expect(JSON.parse(await persistor.getItem(["new.esp"])).enabled).toBeUndefined();
      expect(JSON.parse(await persistor.getItem(["old.esp"])).enabled).toBe(true);
      choose!("keep");
    });

    it("adopts the foreign content when the user chooses keep", async () => {
      persistor.setExternalChangeCallback(() => Promise.resolve("keep"));

      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await vi.waitFor(async () => {
        expect(JSON.parse(await persistor.getItem(["new.esp"])).enabled).toBe(true);
      });
    });

    it("keep adopts the LATEST disk content, not the snapshot that opened the dialog", async () => {
      let choose: (choice: "keep" | "revert") => void;
      persistor.setExternalChangeCallback(
        () => new Promise<"keep" | "revert">((resolve) => (choose = resolve)),
      );

      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();
      // the external tool writes again while the dialog is open
      nodeFs.writeFileSync(pluginsFile(), "*Newer.esp\r\n", { encoding: "latin1" });

      choose!("keep");

      await vi.waitFor(async () => {
        expect(JSON.parse(await persistor.getItem(["newer.esp"])).enabled).toBe(true);
      });
      expect(JSON.parse(await persistor.getItem(["new.esp"])).enabled).toBeUndefined();
    });

    it("keep still adopts the foreign content when Vortex writes while the dialog is open", async () => {
      let choose: (choice: "keep" | "revert") => void;
      persistor.setExternalChangeCallback(
        () => new Promise<"keep" | "revert">((resolve) => (choose = resolve)),
      );

      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();

      // the prompt runs detached from the serialize queue, so Vortex's own writes carry on
      // while the choice is outstanding: a known-plugins refresh schedules one 200ms out
      persistor.setKnownPlugins({ "old.esp": "Old.esp", "parked.esp": "Parked.esp" });
      await settle(300);
      // that write must not land on the contested file, or there is nothing left to keep
      expect(nodeFs.readFileSync(pluginsFile(), "latin1")).toContain("New.esp");

      choose!("keep");

      await vi.waitFor(async () => {
        expect(JSON.parse(await persistor.getItem(["new.esp"])).enabled).toBe(true);
      });
    });

    it("writes Vortex's own state back over the file when the user chooses revert", async () => {
      persistor.setExternalChangeCallback(() => Promise.resolve("revert"));

      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await vi.waitFor(() => {
        const written = nodeFs.readFileSync(pluginsFile(), "latin1");
        expect(written).toContain(VORTEX_HEADER);
        expect(written).toContain("*Old.esp");
        expect(written).not.toContain("New.esp");
      });

      expect(JSON.parse(await persistor.getItem(["new.esp"])).enabled).toBeUndefined();
    });

    it("still adopts silently on the initial import (no prior state)", async () => {
      const onExternalChange = vi.fn(() => Promise.resolve("revert" as const));
      const freshDir = nodeFs.mkdtempSync(path.join(os.tmpdir(), "plugin-fresh-"));
      paths.pluginDir = freshDir;
      nodeFs.writeFileSync(path.join(freshDir, "plugins.txt"), "*New.esp\r\n", {
        encoding: "latin1",
      });
      const fresh = new PluginPersistor(vi.fn(), () => false);
      fresh.setExternalChangeCallback(onExternalChange);
      fresh.setResetCallback(vi.fn(async () => undefined));

      await fresh.loadFiles("skyrimse");
      await settle();

      expect(onExternalChange).not.toHaveBeenCalled();
      expect(JSON.parse(await fresh.getItem(["new.esp"])).enabled).toBe(true);
      await fresh.disable();
      nodeFs.rmSync(freshDir, { recursive: true, force: true });
    });

    it("keeps its state when plugins.txt is momentarily empty", async () => {
      // anti-virus or a crashed write can truncate the file; Vortex's own state is the
      // authority, an empty file is not a statement that every plugin is gone
      nodeFs.writeFileSync(pluginsFile(), "", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();

      expect(JSON.parse(await persistor.getItem(["old.esp"])).enabled).toBe(true);
    });

    it("does not offer the keep/revert choice for an empty plugins.txt", async () => {
      const onExternalChange = vi.fn(() => Promise.resolve("keep" as const));
      persistor.setExternalChangeCallback(onExternalChange);

      nodeFs.writeFileSync(pluginsFile(), "", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();

      // there is nothing to adopt, so there is no choice to make
      expect(onExternalChange).not.toHaveBeenCalled();
    });

    it("re-asserts the plugin files from the known set after loading", async () => {
      // on a profile switch the known-plugins refresh lands while the persistor is
      // disabled, so its serialize is dropped; loading must then write the files back
      // from the refreshed known set or they keep the previous profile's entries
      await persistor.disable();
      persistor.setKnownPlugins({ "new.esp": "New.esp" });

      await persistor.loadFiles("skyrimse");

      await vi.waitFor(() => {
        const written = nodeFs.readFileSync(path.join(paths.pluginDir, "plugins.txt"), "latin1");
        expect(written).toContain("New.esp");
        expect(written).not.toContain("Old.esp");
      });
    });

    it("stays writable after the initial load finds an empty plugins file", async () => {
      const freshDir = nodeFs.mkdtempSync(path.join(os.tmpdir(), "plugin-empty-"));
      paths.pluginDir = freshDir;
      nodeFs.writeFileSync(path.join(freshDir, "plugins.txt"), "", { encoding: "latin1" });
      const fresh = new PluginPersistor(vi.fn(), () => false);
      fresh.setResetCallback(vi.fn(async () => undefined));
      await fresh.loadFiles("skyrimse");

      fresh.setKnownPlugins({ "new.esp": "New.esp" });
      await fresh.setItem(["new.esp"], JSON.stringify({ enabled: true, loadOrder: 0 }));

      await vi.waitFor(() => {
        const written = nodeFs.readFileSync(path.join(freshDir, "plugins.txt"), "latin1");
        expect(written).toContain("*New.esp");
      });
      await fresh.disable();
      nodeFs.rmSync(freshDir, { recursive: true, force: true });
    });

    it("clears a pending choice when the persistor is disabled", async () => {
      // the prompt can outlive the game it was raised for; left pending it blocks the
      // next game's initial read and the hive is never populated
      const onExternalChange = vi.fn(() => new Promise<"keep" | "revert">(() => undefined));
      persistor.setExternalChangeCallback(onExternalChange);
      nodeFs.writeFileSync(pluginsFile(), "*New.esp\r\n", { encoding: "latin1" });
      await persistor.loadFiles("skyrimse");
      await settle();
      // the choice really is outstanding, otherwise this proves nothing
      expect(onExternalChange).toHaveBeenCalledTimes(1);

      await persistor.disable();

      nodeFs.writeFileSync(pluginsFile(), `${VORTEX_HEADER}\r\n*Old.esp\r\n`, {
        encoding: "latin1",
      });
      await persistor.loadFiles("skyrimse");
      await settle();

      // getAllKeys reads mKnownPlugins, which disable() leaves alone, so probe the state
      // deserialize is meant to have rebuilt
      expect(JSON.parse(await persistor.getItem(["old.esp"])).enabled).toBe(true);
    });
  });

  it("syncFromState makes the hive queryable from the persistor and reaches the file", async () => {
    hive["multi.esp"] = { enabled: true, loadOrder: 1 };

    await persistor.syncFromState("skyrimse", hive as Record<string, ILoadOrder>);

    expect(JSON.parse(await persistor.getItem(["multi.esp"])).enabled).toBe(true);

    persistor.setKnownPlugins({ "old.esp": "Old.esp", "multi.esp": "Multi.esp" });
    await vi.waitFor(() => {
      const written = nodeFs.readFileSync(path.join(paths.pluginDir, "plugins.txt"), "latin1");
      expect(written).toContain("*Multi.esp");
      expect(written).toContain("*Old.esp");
    });
  });

  it("syncFromState merges: entries absent from the hive keep their position", async () => {
    expect(JSON.parse(await persistor.getItem(["parked.esp"])).loadOrder).toBeGreaterThanOrEqual(0);

    hive["multi.esp"] = { enabled: true, loadOrder: 1 };
    await persistor.syncFromState("skyrimse", hive as Record<string, ILoadOrder>);

    expect(JSON.parse(await persistor.getItem(["parked.esp"])).loadOrder).toBeGreaterThanOrEqual(0);
  });

  it("syncFromState ignores a sync for a game the persistor is not bound to", async () => {
    hive["multi.esp"] = { enabled: true, loadOrder: 1 };

    await persistor.syncFromState("fallout4", hive as Record<string, ILoadOrder>);

    expect(JSON.parse(await persistor.getItem(["multi.esp"])).enabled).toBeUndefined();
  });

  it("syncFromState ignores an empty hive", async () => {
    await persistor.syncFromState("skyrimse", {});

    expect(JSON.parse(await persistor.getItem(["old.esp"])).enabled).toBe(true);
  });

  it("a malformed hive entry does not poison the write queue", async () => {
    await persistor.syncFromState("skyrimse", { "broken.esp": null } as never);

    hive["multi.esp"] = { enabled: true, loadOrder: 1 };
    await persistor.syncFromState("skyrimse", hive as Record<string, ILoadOrder>);

    expect(JSON.parse(await persistor.getItem(["multi.esp"])).enabled).toBe(true);
  });

  it("rehydrates when the installed-native set changes, and only then", async () => {
    paths.native = ["skyrim.esm"];
    const dir = nodeFs.mkdtempSync(path.join(os.tmpdir(), "plugin-native-"));
    paths.pluginDir = dir;
    nodeFs.writeFileSync(path.join(dir, "plugins.txt"), `${VORTEX_HEADER}\r\n*Old.esp\r\n`, {
      encoding: "latin1",
    });
    const native = new PluginPersistor(vi.fn(), () => false);
    const reset = vi.fn(async () => undefined);
    native.setResetCallback(reset);
    await native.loadFiles("skyrimse");
    const base = reset.mock.calls.length;

    native.setKnownPlugins({ "old.esp": "Old.esp" });
    expect(reset.mock.calls.length).toBe(base);

    native.setKnownPlugins({ "old.esp": "Old.esp", "skyrim.esm": "Skyrim.esm" });
    expect(reset.mock.calls.length).toBe(base + 1);

    await native.disable();
    nodeFs.rmSync(dir, { recursive: true, force: true });
  });
});
