# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json
engineStrict: true

packages:
  - ./src/shared
  - ./src/preload
  - ./src/main
  - ./src/renderer
  - ./extensions/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - ba2tk
  - bsatk
  - bsdiff-node
  - core-js
  - crash-dump
  - diskusage
  - drivelist
  - electron
  - fomod-installer-native
  - font-scanner
  - leveldown
  - native-errors
  - unrs-resolver
  - vortexmt
  - winapi-bindings
  - xxhash-addon
