/* eslint-disable */
import * as React from 'react';
import * as BS from 'react-bootstrap';
import { I18N_NAMESPACE } from '../common';

import { FlexLayout, util } from 'vortex-api';
import { useTranslation } from 'react-i18next';

interface InfoComponentProps {
  onToggleModsState: (enable: boolean) => void;
}

export default function InfoComponent(props: InfoComponentProps) {
  const { onToggleModsState } = props;
  const t = useTranslation(I18N_NAMESPACE).t;
  const toggleModsState = React.useCallback((enable) => {
    onToggleModsState(enable);
  }, [onToggleModsState]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginRight: '16px' }}>
        <div>
          <p>
            {t('You can adjust the load order for The Witcher 3 by dragging and dropping '
              + 'mods up or down on this page.  If you are using several mods that add scripts you may need to use '
              + 'the Witcher 3 Script merger. For more information see: ', { ns: I18N_NAMESPACE })}
            <a onClick={() => util.opn('https://wiki.nexusmods.com/index.php/Modding_The_Witcher_3_with_Vortex')}>
              {t('Modding The Witcher 3 with Vortex.', { ns: I18N_NAMESPACE })}
            </a>
          </p>
        </div>
        <div style={{ height: '80%' }}>
          <p>{t('Please note:', { ns: I18N_NAMESPACE })}</p>
          <ul>
            <li>{t('For Witcher 3, the mod with the lowest index number (by default, the mod sorted at the top) overrides mods with a higher index number.', { ns: I18N_NAMESPACE })}</li>
            <li>{t('If you cannot see your mod in this load order, you may need to add it manually (see our wiki for details).', { ns: I18N_NAMESPACE })}</li>
            <li>{t('When managing menu mods, mod settings changed inside the game will be detected by Vortex as external changes - that is expected, '
              + 'choose to use the newer file and your settings will be made persistent.',
              { ns: I18N_NAMESPACE })}</li>
            <li>{t('Merges generated by the Witcher 3 Script merger must be loaded first and are locked in the first load order slot.', { ns: I18N_NAMESPACE })}</li>
          </ul>
          <BS.Button
            onClick={() => toggleModsState(false)}
            style={{ marginBottom: '5px', width: 'min-content' }}
          >
            {t('Disable All')}
          </BS.Button>
          <br />
          <BS.Button
            onClick={() => toggleModsState(true)}
            style={{ marginBottom: '5px', width: 'min-content' }}
          >
            {t('Enable All ')}
          </BS.Button>
        </div>
      </div>
  );
}
