name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [ 6.0.x ]

    steps:   
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lockfile
          path: ./yarn.lock
          if-no-files-found: error
