/**
 * Cross-module constants used by the Stardew Valley extension.
 *
 * Keep values here stable so installer, runtime, and UI modules share the same
 * identifiers for game IDs, file names, and mod types.
 */
/** Vortex game id for Stardew Valley. */
export const GAME_ID = 'stardewvalley';

/** Standard config file name generated by many SDV mods. */
export const MOD_CONFIG = 'config.json';

/** Standard manifest file name for SMAPI mods. */
export const MOD_MANIFEST = 'manifest.json';

/** Invalid Windows path characters replaced during generated-name sanitization. */
export const RGX_INVALID_CHARS_WINDOWS = /[:/\\*?"<>|]/g;

/** Registered Vortex mod type id for normal SMAPI mods. */
export const MOD_TYPE_SMAPI = 'SMAPI';

/** Registered Vortex mod type id for the generated config mod. */
export const MOD_TYPE_CONFIG = 'sdv-configuration-mod';

/** Registered Vortex mod type id for root-folder deployments. */
export const MOD_TYPE_ROOT = 'sdvrootfolder';

/** Registered installer id for the SMAPI installer archive handler. */
export const INSTALLER_ID_SMAPI = 'smapi-installer';

/** Registered installer id for root-folder archive installs. */
export const INSTALLER_ID_ROOT = 'sdvrootfolder';

/** Registered installer id for manifest-based SDV archives. */
export const INSTALLER_ID_MANIFEST = 'stardew-valley-installer';

/** Installer priority for SMAPI archives. */
export const INSTALLER_PRIORITY_SMAPI = 30;

/** Installer priority for root-folder archives. */
export const INSTALLER_PRIORITY_ROOT = 50;

/** Installer priority for manifest-based archives. */
export const INSTALLER_PRIORITY_MANIFEST = 50;

/** Mod type detection priority for SMAPI mods. */
export const MOD_TYPE_PRIORITY_SMAPI = 30;

/** Mod type detection priority for the generated config mod. */
export const MOD_TYPE_PRIORITY_CONFIG = 30;

/** Mod type detection priority for root-folder mods. */
export const MOD_TYPE_PRIORITY_ROOT = 25;

/** Internal SMAPI folder name that should be excluded from config sync. */
export const SMAPI_INTERNAL_DIRECTORY = 'smapi-internal';

/** Mutable list of bundled SMAPI framework mods detected at runtime. */
export const _SMAPI_BUNDLED_MODS = ['ErrorHandler', 'ConsoleCommands', 'SaveBackup'];

/** Notification id for config-mod import activity toasts. */
export const NOTIF_ACTIVITY_CONFIG_MOD = 'sdv-config-mod-activity';

/** Returns unique bundled SMAPI mod names normalized to lowercase. */
export const getBundledMods = () => {
  return Array.from(new Set(_SMAPI_BUNDLED_MODS.map(modName => modName.toLowerCase())));
}
