/**
 * Cross-module constants used by the Stardew Valley extension.
 *
 * Keep values here stable so installer, runtime, and UI modules share the same
 * identifiers, priorities, and SMAPI integration settings.
 */
/** Vortex game id for Stardew Valley. */
export const GAME_ID = "stardewvalley";

/** Standard config file name generated by many SDV mods. */
export const MOD_CONFIG = "config.json";

/** Standard manifest file name for SMAPI mods. */
export const MOD_MANIFEST = "manifest.json";

/** Standard Mods folder path relative to the game root. */
export const MODS_REL_PATH = "Mods";

/** Invalid Windows path characters replaced during generated-name sanitization. */
export const RGX_INVALID_CHARS_WINDOWS = /[:/\\*?"<>|]/g;

/** Registered Vortex mod type id for normal SMAPI mods. */
export const MOD_TYPE_SMAPI = "SMAPI";

/** Registered Vortex mod type id for the generated config mod. */
export const MOD_TYPE_CONFIG = "sdv-configuration-mod";

/** Registered Vortex mod type id for root-folder deployments. */
export const MOD_TYPE_ROOT = "sdvrootfolder";

/** Registered installer id for the SMAPI installer archive handler. */
export const INSTALLER_ID_SMAPI = "smapi-installer";

/** Registered installer id for root-folder archive installs. */
export const INSTALLER_ID_ROOT = "sdvrootfolder";

/** Registered installer id for manifest-based SDV archives. */
export const INSTALLER_ID_MANIFEST = "stardew-valley-installer";

/** Installer priority for SMAPI archives. */
export const INSTALLER_PRIORITY_SMAPI = 30;

/** Installer priority for root-folder archives. */
export const INSTALLER_PRIORITY_ROOT = 50;

/** Installer priority for manifest-based archives. */
export const INSTALLER_PRIORITY_MANIFEST = 50;

/** Mod type detection priority for SMAPI mods. */
export const MOD_TYPE_PRIORITY_SMAPI = 30;

/** Mod type detection priority for the generated config mod. */
export const MOD_TYPE_PRIORITY_CONFIG = 30;

/** Mod type detection priority for root-folder mods. */
export const MOD_TYPE_PRIORITY_ROOT = 25;

/** Internal SMAPI folder name that should be excluded from config sync. */
export const SMAPI_INTERNAL_DIRECTORY = "smapi-internal";

/** Mutable list of bundled SMAPI framework mods detected at runtime. */
export const _SMAPI_BUNDLED_MODS = ["ErrorHandler", "ConsoleCommands", "SaveBackup"];

/** SMAPI compatibility query interval (once per week). */
export const SMAPI_QUERY_FREQUENCY: number = 1000 * 60 * 24 * 7;

/** SMAPI.io API version used for compatibility lookups. */
export const SMAPI_IO_API_VERSION = "3.0.0";

/** Nexus mod id for the SMAPI package. */
export const SMAPI_MOD_ID = 2400;

/** Public Nexus page for SMAPI downloads. */
export const SMAPI_URL = `https://www.nexusmods.com/stardewvalley/mods/${SMAPI_MOD_ID}`;

/** Notification id for config-mod import activity toasts. */
export const NOTIF_ACTIVITY_CONFIG_MOD = "sdv-config-mod-activity";

/** Returns unique bundled SMAPI mod names normalized to lowercase. */
export const getBundledMods = () => {
  return Array.from(new Set(_SMAPI_BUNDLED_MODS.map((modName) => modName.toLowerCase())));
};
