/**
 * Installation helpers for converting downloaded SMAPI archives into enabled
 * Stardew Valley mods.
 */
import type { types } from 'vortex-api';

import { actions, selectors, util } from 'vortex-api';

import { GAME_ID } from '../common';

/**
 * Installs a previously downloaded SMAPI archive.
 *
 * @param api Vortex extension API (`types.IExtensionApi`) used to emit install
 * events.
 * @param downloadId Download id (`string`) returned by `downloadSMAPI`.
 * @returns Installed mod id (`string`) generated by Vortex.
 */
export async function installDownloadedSMAPI(api: types.IExtensionApi, downloadId: string): Promise<string> {
  return util.toPromise<string>(cb =>
    api.events.emit('start-install-download', downloadId, { allowAutoEnable: false }, cb));
}

/**
 * Enables an installed SMAPI mod for the last active Stardew Valley profile.
 *
 * @param api Vortex extension API (`types.IExtensionApi`) used to resolve
 * profile state and dispatch enable actions.
 * @param modId Installed SMAPI mod id (`string`) returned by
 * `installDownloadedSMAPI`.
 * @returns Resolves when the mod is enabled in profile state.
 */
export async function enableSMAPIMod(api: types.IExtensionApi, modId: string): Promise<void> {
  const profileId = selectors.lastActiveProfileForGame(api.getState(), GAME_ID);
  await actions.setModsEnabled(api, profileId, [modId], true, {
    allowAutoDeploy: false,
    installed: true,
  });
}
