name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install volta, Node.js and Yarn
        uses: volta-cli/action@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Configure node-gyp for VS 2022
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "npm_config_msvs_version=2022" >> $env:GITHUB_ENV
          echo "GYP_MSVS_VERSION=2022" >> $env:GITHUB_ENV

      # NOTE(erri120): fontconfig required by font-scanner required by theme-switcher
      - name: Install fontconfig
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev

      - name: Build FOMOD
        run: pnpm run build:fomod

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:ci

      - name: Build
        run: pnpm run build:all

      - name: Test
        run: pnpm run test
