name: "PR Maintenance"

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types: [synchronize]
  workflow_dispatch:
  schedule:
    - cron: "8 10 * * *" # every day at 10:08 UTC

permissions:
  pull-requests: write

jobs:
  check-dirty:
    runs-on: ubuntu-latest

    steps:
      - name: "Check if PRs are dirty"
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnDirty: "This PR has conflicts. You need to rebase the PR before it can be merged."
          commentOnClean: "This PR doesn't have conflicts anymore. It can be merged after all status checks have passed and it has been reviewed."

  check-stale:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/stale@v10
        with:
          # ignore issues
          days-before-issue-stale: -1
          days-before-issue-close: -1

          days-before-pr-stale: 7
          days-before-pr-close: -1 # don't auto-close stale PRs
          stale-pr-message: "This PR has been marked as stale due to inactivity."
          stale-pr-label: "PR: stale"
